=== volkmarnissen/oci-lxc-deployer/backend/schemas/application.schema.json
{
  "$id": "application",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "extends": { "type": "string", "pattern": "^(local:|[^:]+).*$" },
    "description": { "type": "string" },
    "icon": { "type": "string", "default": "icon.png" },
    "installation": { "$ref": "templatelist.schema.json" },
    "backup": { "$ref": "templatelist.schema.json" },
    "restore": { "$ref": "templatelist.schema.json" },
    "uninstall": { "$ref": "templatelist.schema.json" },
    "update": { "$ref": "templatelist.schema.json" },
    "upgrade": { "$ref": "templatelist.schema.json" }
  },
  "required": ["name", "installation"],
    "additionalProperties": false

}

=== volkmarnissen/oci-lxc-deployer/json/applications/mariadb/application.json
{
  "name": "MariaDB",
  "description": "MariaDB database server",
  "icon": "icon.png",
  "installation": [
    "set-parameters.json",
    "010-get-latest-os-template.json",
    "100-create-lxc.json",
    "200-start-lxc.json",
    "210-wait-for-container-ready.json",
    "330-install-apk-package.json",
    "400-initialize-mariadb.json",
    "430-configure-mariadb.json",
    "410-start-mariadb.json",
    "420-secure-mariadb.json",
    "440-enable-mariadb.json"
  ]
}

=== volkmarnissen/oci-lxc-deployer/json/applications/npm-nodejs/application.json
{
  "name": "npm-nodejs",
  "description": "Base application for Node.js/npm based services",
  "icon": "icon.png",
  "installation": [
    "010-get-latest-os-template.json",
    "100-create-configure-lxc.json",
    "200-start-lxc.json",
    "210-wait-for-container-ready.json",
    "305-set-pkg-mirror.json",
    "330-install-packages.json",
    "340-install-node-application.json",
    "350-create-enable-service.json"
  ]
}

=== volkmarnissen/oci-lxc-deployer/examples/applications/mariadb/application.json
{
  "name": "MariaDB",
  "description": "MariaDB database server with user and database creation",
  "extends": "json:mariadb",
  "installation": [
    "create-db-dynamic-prices.json",
     "450-create-mariadb-user.json",
     "create-db-homeassistant.json",
    "450-create-mariadb-user.json"
  ]
}

=== volkmarnissen/oci-lxc-deployer/json/applications/oci-image/application.json
{
  "name": "oci-image",
  "description": "Base application for OCI image based services",
  "icon": "icon.png",
  "installation": [
    "011-get-oci-image.json",
    "100-create-configure-lxc.json",
    "200-start-lxc.json",
    "210-wait-for-container-ready.json",
    "305-set-pkg-mirror.json"
  ]
}
