=== volkmarnissen/oci-lxc-deployer/schemas/application.schema.json
{
  "$id": "application",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "extends": { "type": "string", "pattern": "^(local:|[^:]+).*$" },
    "description": { "type": "string" },
    "icon": { "type": "string", "default": "icon.png" },
    "url": { "type": "string" },
    "documentation": { "type": "string" },
    "source": { "type": "string" },
    "vendor": { "type": "string" },
    "installation": { "$ref": "templatelist" },
    "copy-upgrade": { "$ref": "templatelist" },
    "copy-rollback": { "$ref": "templatelist" }
  },
  "required": ["name", "installation"],
  "additionalProperties": false
}

=== volkmarnissen/oci-lxc-deployer/json/applications/oci-lxc-deployer/application.json
{
  "name": "OCI LXC Deployer",
  "description": "Deploys and manages LXC containers on Proxmox from OCI images via a web UI and API, and lets you easily define custom container services",
  "extends": "oci-image",
  "icon": "favicon.svg",
  "installation": [
    {
      "name": "oci-lxc-deployer-parameters.json",
      "before": "011-get-oci-image.json"
    }
  ],
  "url": "https://github.com/modbus2mqtt/oci-lxc-deployer",
  "documentation": "https://github.com/modbus2mqtt/oci-lxc-deployer/blob/main/README.md",
  "source": "https://github.com/modbus2mqtt/oci-lxc-deployer",
  "vendor": "Carcam 360"
}

=== volkmarnissen/oci-lxc-deployer/examples/applications/mariadb1/application.json
{
  "name": "Mariadb",
  "description": "MariaDB Database for relational SQL",
  "extends": "oci-image",
  "icon": "icon.svg",
  "installation": [
    {
      "name": "mariadb1-parameters.json",
      "before": "011-get-oci-image.json"
    }
  ],
  "url": "https://github.com/MariaDB/mariadb-docker",
  "documentation": "https://hub.docker.com/_/mariadb/",
  "source": "https://github.com/MariaDB/mariadb-docker",
  "vendor": "MariaDB Community"
}
